http:
  middlewares:
    redirect-to-https:
    redirectScheme:
      scheme: https
  routers:
    http-catchall:
      rule: "HostRegexp(`{any:.+}`)"
      entryPoints: [web]
      middlewares: [redirect-to-https]
      service: noop
  services:
    noop:
      loadBalancer:
        servers:
          - url: http://127.0.0.1