"""m1

Revision ID: 374a5969fa5a
Revises: 
Create Date: 2024-07-25 10:04:33.282103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '374a5969fa5a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('ap_id', sa.String(), nullable=False),
    sa.Column('configuration', sa.JSON(), nullable=False),
    sa.Column('supported_commands', sa.JSON(), nullable=False),
    sa.Column('onboard', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_agents_ap_id'), 'agents', ['ap_id'], unique=True)
    op.create_index(op.f('ix_agents_username'), 'agents', ['username'], unique=True)
    op.create_table('third_party_apps',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('app_name', sa.String(), nullable=False),
    sa.Column('api_key', sa.String(), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_third_party_apps_app_name'), 'third_party_apps', ['app_name'], unique=True)
    op.create_table('users',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('roles', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_third_party_apps_app_name'), table_name='third_party_apps')
    op.drop_table('third_party_apps')
    op.drop_index(op.f('ix_agents_username'), table_name='agents')
    op.drop_index(op.f('ix_agents_ap_id'), table_name='agents')
    op.drop_table('agents')
    # ### end Alembic commands ###
