"""m2

Revision ID: 9c92eaf505fd
Revises: 374a5969fa5a
Create Date: 2024-07-25 16:32:01.797767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9c92eaf505fd'
down_revision: Union[str, None] = '374a5969fa5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agents', 'configuration',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.drop_index('ix_agents_username', table_name='agents')
    op.create_unique_constraint(None, 'agents', ['id'])
    op.drop_column('agents', 'username')
    op.drop_column('agents', 'supported_commands')
    op.create_unique_constraint(None, 'third_party_apps', ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'third_party_apps', type_='unique')
    op.add_column('agents', sa.Column('supported_commands', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('agents', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'agents', type_='unique')
    op.create_index('ix_agents_username', 'agents', ['username'], unique=True)
    op.alter_column('agents', 'configuration',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    # ### end Alembic commands ###
