name: Deploy to Production

on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  deploy:
    runs-on:
      - self-hosted
      - production
    env:
      ENVIRONMENT: production
      DOMAIN: ${{ vars.DOMAIN_PRODUCTION }}
      BACKEND_CORS_ORIGINS: https://${{ vars.DOMAIN_PRODUCTION }}
      EMAILS_FROM_EMAIL: ${{ vars.EMAILS_FROM_EMAIL }}
      STACK_NAME: ${{ vars.STACK_NAME_PRODUCTION }}
      INFLUXDB_PASSWORD: ${{ secrets.INFLUXDB_PASSWORD }}
      CLOUDFLARE_TUNNEL_TOKEN: ${{ secrets.CLOUDFLARE_TUNNEL_TOKEN_PRODUCTION }}
      JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      FIRST_SUPERUSER: ${{ vars.FIRST_SUPERUSER }}
      FIRST_SUPERUSER_PASSWORD: ${{ secrets.FIRST_SUPERUSER_PASSWORD }}
      SMTP_HOST: ${{ secrets.SMTP_HOST }}
      SMTP_USER: ${{ secrets.SMTP_USER }}
      SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: docker compose -f docker-compose.yml -f docker-compose.cloudflare.yml --project-name ${{ vars.STACK_NAME_PRODUCTION }} build
      - run: docker compose -f docker-compose.yml -f docker-compose.cloudflare.yml --project-name ${{ vars.STACK_NAME_PRODUCTION }} up -d