name: Deploy to Staging

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on:
      - self-hosted
      - staging
    env:
      ENVIRONMENT: staging
      DOMAIN: ${{ vars.DOMAIN_STAGING }}
      EMAILS_FROM_EMAIL: ${{ vars.EMAILS_FROM_EMAIL }}
      STACK_NAME: ${{ vars.STACK_NAME_STAGING }}
      INFLUXDB_PASSWORD: ${{ secrets.INFLUXDB_PASSWORD }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      FIRST_SUPERUSER: ${{ vars.FIRST_SUPERUSER }}
      FIRST_SUPERUSER_PASSWORD: ${{ secrets.FIRST_SUPERUSER_PASSWORD }}
      SMTP_HOST: ${{ secrets.SMTP_HOST }}
      SMTP_USER: ${{ secrets.SMTP_USER }}
      SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      # SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: docker compose -f docker-compose.yml -f docker-compose.traefik.yml --project-name ${{ vars.STACK_NAME_STAGING }} build
      - run: docker compose -f docker-compose.yml -f docker-compose.traefik.yml --project-name ${{ vars.STACK_NAME_STAGING }} up -d
